import 'package:flutter/widgets.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

import 'app.dart';

/// Injected at build time via `--dart-define-from-file=env.json`
/// (generated by `tool/gen-env.sh` from the repo-root .env — public values only).
const _supabaseUrl = String.fromEnvironment('SUPABASE_URL');
const _supabasePublishableKey = String.fromEnvironment(
  'SUPABASE_PUBLISHABLE_KEY',
);

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Offline-first: Supabase is optional at runtime. Without config (or without
  // network) the app runs fully local; sync and the version gate no-op/fail open.
  if (_supabaseUrl.isNotEmpty && _supabasePublishableKey.isNotEmpty) {
    try {
      await Supabase.initialize(
        url: _supabaseUrl,
        publishableKey: _supabasePublishableKey,
      );
    } catch (_) {
      // Never block launch on backend init; the gym basement rule applies here too.
    }
  }

  runApp(const ProviderScope(child: WomensGymApp()));
}
