import 'package:programming_engine/programming_engine.dart';

import 'review_form_state.dart';

typedef PersonaPreset = ({String name, ReviewFormState state});

const personaPresets = <PersonaPreset>[
  (
    name: '01 · Maya, 24',
    state: ReviewFormState(
      ageBand: AgeBand.age18To29,
      daysPerWeek: TrainingDaysPerWeek.three,
      sessionMinutes: SessionMinutes.fortyFive,
      goal: Goal.tonedAndDefined,
      emphasis: Emphasis.glutes,
      experienceTier: ProfileExperienceTier.newToIt,
      gymComfort: GymComfort.low,
      weeksTrained: 0,
      mesocycleIndex: 1,
      unitSystem: UnitSystem.metric,
      bodyMassKg: 62,
    ),
  ),
  (
    name: '02 · Dana, 31',
    state: ReviewFormState(
      ageBand: AgeBand.age30To39,
      daysPerWeek: TrainingDaysPerWeek.two,
      sessionMinutes: SessionMinutes.thirty,
      goal: Goal.feelHealthier,
      emphasis: Emphasis.balanced,
      experienceTier: ProfileExperienceTier.beenAWhile,
      gymComfort: GymComfort.mostlyFine,
      weeksTrained: 4,
      mesocycleIndex: 1,
      unitSystem: UnitSystem.metric,
      bodyMassKg: 65,
    ),
  ),
  (
    name: '03 · Ruth, 63',
    state: ReviewFormState(
      ageBand: AgeBand.age60Plus,
      daysPerWeek: TrainingDaysPerWeek.two,
      sessionMinutes: SessionMinutes.fortyFive,
      goal: Goal.feelHealthier,
      emphasis: Emphasis.balanced,
      experienceTier: ProfileExperienceTier.newToIt,
      gymComfort: GymComfort.low,
      weeksTrained: 0,
      mesocycleIndex: 1,
      unitSystem: UnitSystem.metric,
      bodyMassKg: 64,
    ),
  ),
  (
    name: '04 · Shir, 27',
    state: ReviewFormState(
      ageBand: AgeBand.age18To29,
      daysPerWeek: TrainingDaysPerWeek.four,
      sessionMinutes: SessionMinutes.sixty,
      goal: Goal.buildCurves,
      emphasis: Emphasis.glutes,
      experienceTier: ProfileExperienceTier.trainsRegularly,
      gymComfort: GymComfort.totallyAtHome,
      weeksTrained: 12,
      mesocycleIndex: 1,
      unitSystem: UnitSystem.metric,
      bodyMassKg: 67,
    ),
  ),
  (
    name: '05 · Noa, 35',
    state: ReviewFormState(
      ageBand: AgeBand.age30To39,
      daysPerWeek: TrainingDaysPerWeek.three,
      sessionMinutes: SessionMinutes.sixty,
      goal: Goal.stronger,
      emphasis: Emphasis.balanced,
      experienceTier: ProfileExperienceTier.beenAWhile,
      gymComfort: GymComfort.mostlyFine,
      weeksTrained: 8,
      mesocycleIndex: 1,
      unitSystem: UnitSystem.metric,
      bodyMassKg: 70,
    ),
  ),
  (
    name: '06 · Lior, 22',
    state: ReviewFormState(
      ageBand: AgeBand.age18To29,
      daysPerWeek: TrainingDaysPerWeek.three,
      sessionMinutes: SessionMinutes.thirty,
      goal: Goal.tonedAndDefined,
      emphasis: Emphasis.glutes,
      experienceTier: ProfileExperienceTier.newToIt,
      gymComfort: GymComfort.low,
      weeksTrained: 0,
      mesocycleIndex: 1,
      unitSystem: UnitSystem.metric,
      bodyMassKg: 58,
    ),
  ),
  (
    name: '07 · Tamar, 45',
    state: ReviewFormState(
      ageBand: AgeBand.age40To49,
      daysPerWeek: TrainingDaysPerWeek.three,
      sessionMinutes: SessionMinutes.fortyFive,
      goal: Goal.tonedAndDefined,
      emphasis: Emphasis.core,
      experienceTier: ProfileExperienceTier.beenAWhile,
      gymComfort: GymComfort.mostlyFine,
      weeksTrained: 8,
      mesocycleIndex: 1,
      unitSystem: UnitSystem.metric,
      bodyMassKg: 66,
    ),
  ),
  (
    name: '08 · Vered, 52',
    state: ReviewFormState(
      ageBand: AgeBand.age50To59,
      daysPerWeek: TrainingDaysPerWeek.two,
      sessionMinutes: SessionMinutes.fortyFive,
      goal: Goal.stronger,
      emphasis: Emphasis.balanced,
      experienceTier: ProfileExperienceTier.beenAWhile,
      gymComfort: GymComfort.mostlyFine,
      weeksTrained: 0,
      mesocycleIndex: 1,
      unitSystem: UnitSystem.metric,
      bodyMassKg: 68,
    ),
  ),
  (
    name: '09 · Alma, 29, runs',
    state: ReviewFormState(
      ageBand: AgeBand.age18To29,
      daysPerWeek: TrainingDaysPerWeek.two,
      sessionMinutes: SessionMinutes.fortyFive,
      goal: Goal.tonedAndDefined,
      emphasis: Emphasis.balanced,
      experienceTier: ProfileExperienceTier.beenAWhile,
      gymComfort: GymComfort.mostlyFine,
      weeksTrained: 8,
      mesocycleIndex: 1,
      unitSystem: UnitSystem.metric,
      bodyMassKg: 61,
      otherActivities: <ActivityKind, int>{ActivityKind.running: 3},
    ),
  ),
  (
    name: '10 · Yael, 33',
    state: ReviewFormState(
      ageBand: AgeBand.age30To39,
      daysPerWeek: TrainingDaysPerWeek.four,
      sessionMinutes: SessionMinutes.fortyFive,
      goal: Goal.buildCurves,
      emphasis: Emphasis.back,
      experienceTier: ProfileExperienceTier.trainsRegularly,
      gymComfort: GymComfort.totallyAtHome,
      weeksTrained: 12,
      mesocycleIndex: 1,
      unitSystem: UnitSystem.metric,
      bodyMassKg: 64,
    ),
  ),
  (
    name: '11 · Roni, 26',
    state: ReviewFormState(
      ageBand: AgeBand.age18To29,
      daysPerWeek: TrainingDaysPerWeek.three,
      sessionMinutes: SessionMinutes.fortyFive,
      goal: Goal.tonedAndDefined,
      emphasis: Emphasis.arms,
      experienceTier: ProfileExperienceTier.beenAWhile,
      gymComfort: GymComfort.mostlyFine,
      weeksTrained: 8,
      mesocycleIndex: 1,
      unitSystem: UnitSystem.metric,
      bodyMassKg: 63,
    ),
  ),
  (
    name: '12 · Michal, 40',
    state: ReviewFormState(
      ageBand: AgeBand.age40To49,
      daysPerWeek: TrainingDaysPerWeek.three,
      sessionMinutes: SessionMinutes.fortyFive,
      goal: Goal.feelHealthier,
      emphasis: Emphasis.balanced,
      experienceTier: ProfileExperienceTier.trainsRegularly,
      gymComfort: GymComfort.totallyAtHome,
      weeksTrained: 12,
      mesocycleIndex: 1,
      unitSystem: UnitSystem.metric,
      bodyMassKg: 65,
    ),
  ),
  (
    name: '13 · Maya, mesocycle 2',
    state: ReviewFormState(
      ageBand: AgeBand.age18To29,
      daysPerWeek: TrainingDaysPerWeek.three,
      sessionMinutes: SessionMinutes.fortyFive,
      goal: Goal.tonedAndDefined,
      emphasis: Emphasis.glutes,
      experienceTier: ProfileExperienceTier.newToIt,
      gymComfort: GymComfort.low,
      weeksTrained: 0,
      mesocycleIndex: 2,
      unitSystem: UnitSystem.metric,
      bodyMassKg: 62,
    ),
  ),
  (
    name: '14 · Efrat, 58',
    state: ReviewFormState(
      ageBand: AgeBand.age50To59,
      daysPerWeek: TrainingDaysPerWeek.three,
      sessionMinutes: SessionMinutes.fortyFive,
      goal: Goal.tonedAndDefined,
      emphasis: Emphasis.glutes,
      experienceTier: ProfileExperienceTier.newToIt,
      gymComfort: GymComfort.low,
      weeksTrained: 0,
      mesocycleIndex: 1,
      unitSystem: UnitSystem.metric,
      bodyMassKg: 69,
    ),
  ),
];
