// Generates the deterministic Supabase content seed.
// Run from packages/programming_engine:
// dart run tool/export_content_sql.dart > ../../supabase/migrations/0003_seed.sql
import 'dart:convert';

import 'package:programming_engine/programming_engine.dart';

const _updatedAt = '2026-07-26T00:00:00.000Z';

void main() {
  final output = StringBuffer()
    ..writeln(
      '-- Generated by packages/programming_engine/tool/'
      'export_content_sql.dart.',
    )
    ..writeln('-- Re-run the exporter after changing catalogV1.')
    ..writeln()
    ..writeln('insert into public.version_gate (')
    ..writeln(
      '  id, recommended_version, min_supported_version, message, '
      'updated_at',
    )
    ..writeln(') values (')
    ..writeln("  true, '0.1.0', '0.1.0', null, '${_updatedAt}'::timestamptz")
    ..writeln(')')
    ..writeln('on conflict (id) do update set')
    ..writeln('  recommended_version = excluded.recommended_version,')
    ..writeln('  min_supported_version = excluded.min_supported_version,')
    ..writeln('  message = excluded.message,')
    ..writeln('  updated_at = excluded.updated_at;')
    ..writeln();

  _writeExercises(output);
  _writeExerciseCopy(output);
  _writeSwapEdges(output);

  // ignore: avoid_print
  print(output.toString());
}

void _writeExercises(StringBuffer output) {
  const columns = <String>[
    'id',
    'slug',
    'name',
    'movement_class',
    'block_role',
    'metric_type',
    'laterality',
    'bw_contribution',
    'load_step_override_kg',
    'resistance_equipment',
    'support_equipment',
    'target_muscles',
    'primary_joint_actions',
    'secondary_joint_actions',
    'rom_rank',
    'stability_rank',
    'difficulty_tier',
    'min_experience',
    'intimidation_tier',
    'age_eligibility',
    'safety_eligibility',
    'machine_lean_ok',
    'seated_variant',
    'retired_at',
    'updated_at',
  ];
  final rows = <List<String>>[
    for (final exercise in catalogV1.exercises)
      <String>[
        _text(exercise.id),
        _text(exercise.slug),
        _text(exercise.name),
        _text(exercise.movementClass.name),
        _text(exercise.blockRole.name),
        _text(exercise.metricType.name),
        _text(exercise.laterality.name),
        _number(exercise.bwContribution),
        _nullableNumber(exercise.loadStepOverride?.value),
        _text(exercise.resistanceEquipment.name),
        _text(exercise.supportEquipment.name),
        _json([
          for (final target in exercise.targetMuscles)
            {'muscle': target.muscle.name, 'role': target.role.name},
        ]),
        _json([for (final action in exercise.primaryJointActions) action.name]),
        _json([
          for (final action in exercise.secondaryJointActions) action.name,
        ]),
        '${exercise.romRank}',
        '${exercise.stabilityRank}',
        _text(exercise.difficultyTier.name),
        _text(exercise.minExperience.name),
        _text(exercise.intimidationTier.name),
        _text(exercise.ageEligibility.name),
        _text(exercise.safetyEligibility.name),
        '${exercise.machineLeanOk}',
        '${exercise.seatedVariant}',
        exercise.retiredAt == null
            ? 'null'
            : "${_text(exercise.retiredAt!.toUtc().toIso8601String())}"
                  '::timestamptz',
        "'$_updatedAt'::timestamptz",
      ],
  ];
  _writeUpsert(output, 'exercises', columns, rows, const ['id']);
}

void _writeExerciseCopy(StringBuffer output) {
  const columns = <String>[
    'exercise_id',
    'setup_steps',
    'should_feel',
    'stop_if',
    'find_it',
    'dos',
    'donts',
    'updated_at',
  ];
  final rows = <List<String>>[
    for (final exercise in catalogV1.exercises)
      <String>[
        _text(exercise.id),
        _json(exercise.setupSteps),
        _text(exercise.shouldFeel),
        _text(exercise.stopIf),
        _text(exercise.findIt),
        _json(exercise.dos),
        _json(exercise.donts),
        "'$_updatedAt'::timestamptz",
      ],
  ];
  _writeUpsert(output, 'exercise_copy', columns, rows, const ['exercise_id']);
}

void _writeSwapEdges(StringBuffer output) {
  const columns = <String>[
    'from_id',
    'to_id',
    'reason',
    'rank',
    'tier',
    'updated_at',
  ];
  final rankBySource = <String, int>{};
  final rows = <List<String>>[];
  for (final edge in catalogV1.swapEdges) {
    final rank = rankBySource.update(
      edge.fromId,
      (value) => value + 1,
      ifAbsent: () => 0,
    );
    for (final reason in SwapReason.values) {
      rows.add([
        _text(edge.fromId),
        _text(edge.toId),
        _text(reason.name),
        '$rank',
        '${edge.tier}',
        "'$_updatedAt'::timestamptz",
      ]);
    }
  }
  _writeUpsert(output, 'swap_edges', columns, rows, const [
    'from_id',
    'to_id',
    'reason',
  ]);
}

void _writeUpsert(
  StringBuffer output,
  String table,
  List<String> columns,
  List<List<String>> rows,
  List<String> conflictColumns,
) {
  output
    ..writeln('insert into public.$table (')
    ..writeln('  ${columns.join(', ')}')
    ..writeln(') values');
  for (var index = 0; index < rows.length; index++) {
    output
      ..write('  (${rows[index].join(', ')})')
      ..writeln(index == rows.length - 1 ? '' : ',');
  }
  final mutableColumns = columns
      .where((column) => !conflictColumns.contains(column))
      .toList(growable: false);
  output..writeln('on conflict (${conflictColumns.join(', ')}) do update set');
  for (var index = 0; index < mutableColumns.length; index++) {
    final column = mutableColumns[index];
    output
      ..write('  $column = excluded.$column')
      ..writeln(index == mutableColumns.length - 1 ? ';' : ',');
  }
  output.writeln();
}

String _text(String value) => "'${value.replaceAll("'", "''")}'";

String _json(Object? value) => '${_text(jsonEncode(value))}::jsonb';

String _number(num value) => value.toString();

String _nullableNumber(num? value) => value == null ? 'null' : _number(value);
