/// v1 fixture/seed catalog.
///
/// values DRAFT pending instructor review
///
/// In particular, `bwContribution`, biomechanics ranks, reason-specific swap
/// ordering, and copy are seed-quality drafts. IDs and the 39-exercise membership
/// follow `docs/EXERCISES.md`.
library;

import '../core/events.dart';
import '../core/prescription.dart';
import 'exercise.dart';

final ContentCatalog catalogV1 = ContentCatalogData(
  contentVersion: 'catalog-v1-draft-2026-07-25',
  exercises: _exercises,
  swapEdges: _swapEdges,
  rotatingBlockRoles: const <BlockRole>{
    BlockRole.lowerSquat,
    BlockRole.lowerHinge,
    BlockRole.upperPush,
    BlockRole.upperPull,
    BlockRole.gluteIsolation,
    BlockRole.armShoulderIsolation,
    BlockRole.core,
  },
);

final List<Exercise> _exercises = <Exercise>[
  // Lower — squat pattern.
  _exercise(
    id: 'dumbbell-goblet-squat',
    name: 'Goblet Squat',
    slug: 'dumbbell-goblet-squat',
    role: BlockRole.lowerSquat,
    movement: MovementClass.compoundLower,
    equipment: ResistanceEquipment.dumbbell,
    bw: 0.65,
    primary: const [MuscleGroup.quads, MuscleGroup.glutes],
    secondary: const [MuscleGroup.core],
    actions: const [JointAction.kneeExtension, JointAction.hipExtension],
    secondaryActions: const [JointAction.trunkBrace, JointAction.grip],
    rom: 4,
    stability: 3,
  ),
  _exercise(
    id: 'barbell-squat',
    name: 'Barbell Back Squat',
    slug: 'barbell-squat',
    role: BlockRole.lowerSquat,
    movement: MovementClass.compoundLower,
    equipment: ResistanceEquipment.barbell,
    support: SupportEquipment.rack,
    bw: 0.85,
    primary: const [MuscleGroup.quads, MuscleGroup.glutes],
    secondary: const [MuscleGroup.core],
    actions: const [JointAction.kneeExtension, JointAction.hipExtension],
    secondaryActions: const [JointAction.trunkBrace],
    rom: 5,
    stability: 4,
    intimidation: IntimidationTier.high,
  ),
  _exercise(
    id: 'machine-leg-press',
    name: 'Leg Press',
    slug: 'machine-leg-press',
    role: BlockRole.lowerSquat,
    movement: MovementClass.compoundLower,
    equipment: ResistanceEquipment.machine,
    bw: 0,
    primary: const [MuscleGroup.quads, MuscleGroup.glutes],
    actions: const [JointAction.kneeExtension, JointAction.hipExtension],
    rom: 4,
    stability: 1,
    machineLean: true,
    seated: true,
  ),
  _exercise(
    id: 'dumbbell-bulgarian-split-squat',
    name: 'Bulgarian Split Squat',
    slug: 'dumbbell-bulgarian-split-squat',
    role: BlockRole.lowerSquat,
    movement: MovementClass.compoundLower,
    metric: MetricType.loadReps,
    equipment: ResistanceEquipment.dumbbell,
    support: SupportEquipment.bench,
    laterality: Laterality.perSide,
    bw: 0.75,
    primary: const [MuscleGroup.quads, MuscleGroup.glutes],
    secondary: const [MuscleGroup.core],
    actions: const [JointAction.kneeExtension, JointAction.hipExtension],
    secondaryActions: const [JointAction.trunkBrace],
    rom: 5,
    stability: 5,
    intimidation: IntimidationTier.moderate,
  ),
  _exercise(
    id: 'bodyweight-squat',
    name: 'Bodyweight Squat',
    slug: 'bodyweight-squat',
    role: BlockRole.lowerSquat,
    movement: MovementClass.compoundLower,
    metric: MetricType.repsOnly,
    equipment: ResistanceEquipment.bodyweight,
    bw: 0.65,
    primary: const [MuscleGroup.quads, MuscleGroup.glutes],
    secondary: const [MuscleGroup.core],
    actions: const [JointAction.kneeExtension, JointAction.hipExtension],
    secondaryActions: const [JointAction.trunkBrace],
    rom: 4,
    stability: 2,
    machineLean: true,
  ),
  _exercise(
    id: 'bodyweight-reverse-lunge',
    name: 'Reverse Lunge',
    slug: 'bodyweight-reverse-lunge',
    role: BlockRole.lowerSquat,
    movement: MovementClass.compoundLower,
    metric: MetricType.repsOnly,
    equipment: ResistanceEquipment.bodyweight,
    laterality: Laterality.perSide,
    bw: 0.75,
    primary: const [MuscleGroup.quads, MuscleGroup.glutes],
    secondary: const [MuscleGroup.core],
    actions: const [JointAction.kneeExtension, JointAction.hipExtension],
    secondaryActions: const [JointAction.trunkBrace],
    rom: 4,
    stability: 4,
  ),

  // Lower — hinge pattern.
  _exercise(
    id: 'barbell-romanian-deadlift',
    name: 'Barbell Romanian Deadlift',
    slug: 'barbell-romanian-deadlift',
    role: BlockRole.lowerHinge,
    movement: MovementClass.compoundLower,
    equipment: ResistanceEquipment.barbell,
    bw: 0.55,
    primary: const [MuscleGroup.hamstrings, MuscleGroup.glutes],
    secondary: const [MuscleGroup.lowerBack, MuscleGroup.forearms],
    actions: const [JointAction.hipExtension],
    secondaryActions: const [JointAction.trunkBrace, JointAction.grip],
    rom: 4,
    stability: 4,
    intimidation: IntimidationTier.moderate,
  ),
  _exercise(
    id: 'dumbbell-romanian-deadlift',
    name: 'Dumbbell Romanian Deadlift',
    slug: 'dumbbell-romanian-deadlift',
    role: BlockRole.lowerHinge,
    movement: MovementClass.compoundLower,
    equipment: ResistanceEquipment.dumbbell,
    bw: 0.55,
    primary: const [MuscleGroup.hamstrings, MuscleGroup.glutes],
    secondary: const [MuscleGroup.lowerBack, MuscleGroup.forearms],
    actions: const [JointAction.hipExtension],
    secondaryActions: const [JointAction.trunkBrace, JointAction.grip],
    rom: 4,
    stability: 3,
  ),
  _exercise(
    id: 'barbell-deadlift',
    name: 'Barbell Deadlift',
    slug: 'barbell-deadlift',
    role: BlockRole.lowerHinge,
    movement: MovementClass.compoundLower,
    equipment: ResistanceEquipment.barbell,
    support: SupportEquipment.platform,
    bw: 0.80,
    primary: const [MuscleGroup.glutes, MuscleGroup.hamstrings],
    secondary: const [
      MuscleGroup.quads,
      MuscleGroup.lowerBack,
      MuscleGroup.forearms,
    ],
    actions: const [JointAction.hipExtension, JointAction.kneeExtension],
    secondaryActions: const [JointAction.trunkBrace, JointAction.grip],
    rom: 5,
    stability: 5,
    intimidation: IntimidationTier.high,
  ),
  _exercise(
    id: 'cable-pull-through',
    name: 'Cable Pull-Through',
    slug: 'cable-pull-through',
    role: BlockRole.lowerHinge,
    movement: MovementClass.compoundLower,
    equipment: ResistanceEquipment.cable,
    bw: 0.45,
    primary: const [MuscleGroup.glutes, MuscleGroup.hamstrings],
    secondary: const [MuscleGroup.core],
    actions: const [JointAction.hipExtension],
    secondaryActions: const [JointAction.trunkBrace],
    rom: 4,
    stability: 2,
    machineLean: true,
    intimidation: IntimidationTier.moderate,
  ),
  _exercise(
    id: 'machine-back-extension',
    name: 'Back Extension',
    slug: 'machine-back-extension',
    role: BlockRole.lowerHinge,
    movement: MovementClass.compoundLower,
    equipment: ResistanceEquipment.machine,
    bw: 0.45,
    primary: const [MuscleGroup.glutes, MuscleGroup.hamstrings],
    secondary: const [MuscleGroup.lowerBack],
    actions: const [JointAction.hipExtension],
    secondaryActions: const [JointAction.spinalExtension],
    rom: 3,
    stability: 1,
    machineLean: true,
    seated: true,
  ),

  // Glutes.
  _exercise(
    id: 'barbell-hip-thrust',
    name: 'Barbell Hip Thrust',
    slug: 'barbell-hip-thrust',
    role: BlockRole.gluteIsolation,
    movement: MovementClass.isolationLower,
    equipment: ResistanceEquipment.barbell,
    support: SupportEquipment.hipThrustPad,
    bw: 0.40,
    primary: const [MuscleGroup.glutes],
    secondary: const [MuscleGroup.hamstrings],
    actions: const [JointAction.hipExtension],
    rom: 3,
    stability: 3,
    intimidation: IntimidationTier.high,
  ),
  _exercise(
    id: 'dumbbell-glute-bridge',
    name: 'Dumbbell Glute Bridge',
    slug: 'dumbbell-glute-bridge',
    role: BlockRole.gluteIsolation,
    movement: MovementClass.isolationLower,
    equipment: ResistanceEquipment.dumbbell,
    support: SupportEquipment.mat,
    bw: 0.40,
    primary: const [MuscleGroup.glutes],
    secondary: const [MuscleGroup.hamstrings],
    actions: const [JointAction.hipExtension],
    rom: 3,
    stability: 1,
    machineLean: true,
  ),
  _exercise(
    id: 'dumbbell-hip-thrust',
    name: 'Dumbbell Hip Thrust',
    slug: 'dumbbell-hip-thrust',
    role: BlockRole.gluteIsolation,
    movement: MovementClass.isolationLower,
    equipment: ResistanceEquipment.dumbbell,
    support: SupportEquipment.bench,
    bw: 0.40,
    primary: const [MuscleGroup.glutes],
    secondary: const [MuscleGroup.hamstrings],
    actions: const [JointAction.hipExtension],
    rom: 3,
    stability: 2,
    intimidation: IntimidationTier.moderate,
  ),
  _exercise(
    id: 'machine-hip-abduction',
    name: 'Hip Abduction Machine',
    slug: 'machine-hip-abduction',
    role: BlockRole.gluteIsolation,
    movement: MovementClass.isolationLower,
    equipment: ResistanceEquipment.machine,
    bw: 0,
    primary: const [MuscleGroup.abductors, MuscleGroup.glutes],
    actions: const [JointAction.hipAbduction],
    rom: 2,
    stability: 1,
    machineLean: true,
    seated: true,
  ),
  _exercise(
    id: 'cable-standing-glute-kickback',
    name: 'Cable Glute Kickback',
    slug: 'cable-standing-glute-kickback',
    role: BlockRole.gluteIsolation,
    movement: MovementClass.isolationLower,
    equipment: ResistanceEquipment.cable,
    bw: 0.10,
    primary: const [MuscleGroup.glutes],
    actions: const [JointAction.hipExtension],
    rom: 3,
    stability: 3,
    intimidation: IntimidationTier.moderate,
  ),
  _exercise(
    id: 'machine-glute-kickback',
    name: 'Machine Glute Kickback',
    slug: 'machine-glute-kickback',
    role: BlockRole.gluteIsolation,
    movement: MovementClass.isolationLower,
    equipment: ResistanceEquipment.machine,
    bw: 0.10,
    primary: const [MuscleGroup.glutes],
    actions: const [JointAction.hipExtension],
    rom: 3,
    stability: 1,
    machineLean: true,
  ),

  // Legs — isolation.
  _exercise(
    id: 'machine-leg-extension',
    name: 'Leg Extension',
    slug: 'machine-leg-extension',
    role: BlockRole.legIsolation,
    movement: MovementClass.isolationLower,
    equipment: ResistanceEquipment.machine,
    bw: 0,
    primary: const [MuscleGroup.quads],
    actions: const [JointAction.kneeExtension],
    rom: 3,
    stability: 1,
    machineLean: true,
    seated: true,
  ),
  _exercise(
    id: 'machine-seated-hamstring-curl',
    name: 'Seated Hamstring Curl',
    slug: 'machine-seated-hamstring-curl',
    role: BlockRole.legIsolation,
    movement: MovementClass.isolationLower,
    equipment: ResistanceEquipment.machine,
    bw: 0,
    primary: const [MuscleGroup.hamstrings],
    actions: const [JointAction.kneeFlexion],
    rom: 3,
    stability: 1,
    machineLean: true,
    seated: true,
  ),
  _exercise(
    id: 'machine-standing-calf-raises',
    name: 'Standing Calf Raise',
    slug: 'machine-standing-calf-raises',
    role: BlockRole.legIsolation,
    movement: MovementClass.isolationLower,
    equipment: ResistanceEquipment.machine,
    bw: 0.90,
    primary: const [MuscleGroup.calves],
    actions: const [JointAction.anklePlantarflexion],
    rom: 3,
    stability: 2,
    machineLean: true,
  ),

  // Upper — push.
  _exercise(
    id: 'dumbbell-bench-press',
    name: 'Dumbbell Bench Press',
    slug: 'dumbbell-bench-press',
    role: BlockRole.upperPush,
    movement: MovementClass.compoundUpperPush,
    equipment: ResistanceEquipment.dumbbell,
    support: SupportEquipment.bench,
    bw: 0,
    primary: const [MuscleGroup.chest, MuscleGroup.triceps],
    secondary: const [MuscleGroup.shoulders],
    actions: const [JointAction.horizontalPush],
    secondaryActions: const [JointAction.elbowExtension],
    rom: 4,
    stability: 3,
    intimidation: IntimidationTier.moderate,
  ),
  _exercise(
    id: 'barbell-bench-press',
    name: 'Barbell Bench Press',
    slug: 'barbell-bench-press',
    role: BlockRole.upperPush,
    movement: MovementClass.compoundUpperPush,
    equipment: ResistanceEquipment.barbell,
    support: SupportEquipment.bench,
    bw: 0,
    primary: const [MuscleGroup.chest, MuscleGroup.triceps],
    secondary: const [MuscleGroup.shoulders],
    actions: const [JointAction.horizontalPush],
    secondaryActions: const [JointAction.elbowExtension],
    rom: 4,
    stability: 4,
    intimidation: IntimidationTier.high,
  ),
  _exercise(
    id: 'machine-chest-press',
    name: 'Machine Chest Press',
    slug: 'machine-chest-press',
    role: BlockRole.upperPush,
    movement: MovementClass.compoundUpperPush,
    equipment: ResistanceEquipment.machine,
    bw: 0,
    primary: const [MuscleGroup.chest, MuscleGroup.triceps],
    secondary: const [MuscleGroup.shoulders],
    actions: const [JointAction.horizontalPush],
    secondaryActions: const [JointAction.elbowExtension],
    rom: 3,
    stability: 1,
    machineLean: true,
    seated: true,
  ),
  _exercise(
    id: 'dumbbell-incline-bench-press',
    name: 'Incline Dumbbell Press',
    slug: 'dumbbell-incline-bench-press',
    role: BlockRole.upperPush,
    movement: MovementClass.compoundUpperPush,
    equipment: ResistanceEquipment.dumbbell,
    support: SupportEquipment.inclineBench,
    bw: 0,
    primary: const [MuscleGroup.chest, MuscleGroup.shoulders],
    secondary: const [MuscleGroup.triceps],
    actions: const [JointAction.horizontalPush, JointAction.shoulderFlexion],
    secondaryActions: const [JointAction.elbowExtension],
    rom: 4,
    stability: 3,
    intimidation: IntimidationTier.moderate,
  ),
  _exercise(
    id: 'dumbbell-seated-overhead-press',
    name: 'Seated Dumbbell Shoulder Press',
    slug: 'dumbbell-seated-overhead-press',
    role: BlockRole.upperPush,
    movement: MovementClass.compoundUpperPush,
    equipment: ResistanceEquipment.dumbbell,
    support: SupportEquipment.bench,
    bw: 0,
    primary: const [MuscleGroup.shoulders, MuscleGroup.triceps],
    actions: const [JointAction.verticalPush],
    secondaryActions: const [JointAction.elbowExtension],
    rom: 4,
    stability: 2,
    machineLean: true,
    seated: true,
  ),
  _exercise(
    id: 'bodyweight-push-up',
    name: 'Push-Up',
    slug: 'bodyweight-push-up',
    role: BlockRole.upperPush,
    movement: MovementClass.compoundUpperPush,
    metric: MetricType.repsOnly,
    equipment: ResistanceEquipment.bodyweight,
    bw: 0.65,
    primary: const [MuscleGroup.chest, MuscleGroup.triceps],
    secondary: const [MuscleGroup.shoulders, MuscleGroup.core],
    actions: const [JointAction.horizontalPush],
    secondaryActions: const [
      JointAction.elbowExtension,
      JointAction.trunkBrace,
    ],
    rom: 4,
    stability: 3,
    machineLean: true,
  ),

  // Upper — pull.
  _exercise(
    id: 'machine-pulldown',
    name: 'Lat Pulldown',
    slug: 'machine-pulldown',
    role: BlockRole.upperPull,
    movement: MovementClass.compoundUpperPull,
    equipment: ResistanceEquipment.machine,
    bw: 0,
    primary: const [MuscleGroup.lats, MuscleGroup.biceps],
    secondary: const [MuscleGroup.upperBack],
    actions: const [JointAction.verticalPull],
    secondaryActions: const [JointAction.elbowFlexion],
    rom: 4,
    stability: 1,
    machineLean: true,
    seated: true,
  ),
  _exercise(
    id: 'machine-seated-cable-row',
    name: 'Seated Cable Row',
    slug: 'machine-seated-cable-row',
    role: BlockRole.upperPull,
    movement: MovementClass.compoundUpperPull,
    equipment: ResistanceEquipment.machine,
    bw: 0,
    primary: const [MuscleGroup.upperBack, MuscleGroup.lats],
    secondary: const [MuscleGroup.biceps],
    actions: const [JointAction.horizontalPull, JointAction.scapularRetraction],
    secondaryActions: const [JointAction.elbowFlexion],
    rom: 4,
    stability: 1,
    machineLean: true,
    seated: true,
  ),
  _exercise(
    id: 'dumbbell-row-unilateral',
    name: 'Single-Arm Dumbbell Row',
    slug: 'dumbbell-row-unilateral',
    role: BlockRole.upperPull,
    movement: MovementClass.compoundUpperPull,
    equipment: ResistanceEquipment.dumbbell,
    support: SupportEquipment.bench,
    laterality: Laterality.perSide,
    bw: 0,
    primary: const [MuscleGroup.lats, MuscleGroup.upperBack],
    secondary: const [MuscleGroup.biceps],
    actions: const [JointAction.horizontalPull],
    secondaryActions: const [JointAction.elbowFlexion, JointAction.grip],
    rom: 4,
    stability: 3,
    intimidation: IntimidationTier.moderate,
  ),
  _exercise(
    id: 'bodyweight-assisted-chin-up',
    name: 'Assisted Pull-Up',
    slug: 'bodyweight-assisted-chin-up',
    role: BlockRole.upperPull,
    movement: MovementClass.compoundUpperPull,
    equipment: ResistanceEquipment.machine,
    bw: 0.85,
    primary: const [MuscleGroup.lats, MuscleGroup.biceps],
    secondary: const [MuscleGroup.upperBack],
    actions: const [JointAction.verticalPull],
    secondaryActions: const [JointAction.elbowFlexion],
    rom: 5,
    stability: 2,
    machineLean: true,
    seated: true,
    intimidation: IntimidationTier.moderate,
  ),
  _exercise(
    id: 'machine-rear-deltoid-row',
    name: 'Machine Rear-Delt Row',
    slug: 'machine-rear-deltoid-row',
    role: BlockRole.upperPull,
    movement: MovementClass.compoundUpperPull,
    equipment: ResistanceEquipment.machine,
    bw: 0,
    primary: const [MuscleGroup.rearDelts, MuscleGroup.upperBack],
    secondary: const [MuscleGroup.biceps],
    actions: const [JointAction.horizontalPull, JointAction.scapularRetraction],
    secondaryActions: const [JointAction.elbowFlexion],
    rom: 3,
    stability: 1,
    machineLean: true,
    seated: true,
  ),

  // Shoulders and arms.
  _exercise(
    id: 'dumbbell-lateral-raise',
    name: 'Dumbbell Lateral Raise',
    slug: 'dumbbell-lateral-raise',
    role: BlockRole.armShoulderIsolation,
    movement: MovementClass.isolationUpper,
    equipment: ResistanceEquipment.dumbbell,
    bw: 0,
    primary: const [MuscleGroup.shoulders],
    actions: const [JointAction.shoulderAbduction],
    rom: 3,
    stability: 2,
  ),
  _exercise(
    id: 'dumbbell-curl',
    name: 'Dumbbell Curl',
    slug: 'dumbbell-curl',
    role: BlockRole.armShoulderIsolation,
    movement: MovementClass.isolationUpper,
    equipment: ResistanceEquipment.dumbbell,
    bw: 0,
    primary: const [MuscleGroup.biceps],
    secondary: const [MuscleGroup.forearms],
    actions: const [JointAction.elbowFlexion],
    secondaryActions: const [JointAction.grip],
    rom: 3,
    stability: 2,
  ),
  _exercise(
    id: 'cable-rope-pushdown',
    name: 'Cable Rope Pushdown',
    slug: 'cable-rope-pushdown',
    role: BlockRole.armShoulderIsolation,
    movement: MovementClass.isolationUpper,
    equipment: ResistanceEquipment.cable,
    bw: 0,
    primary: const [MuscleGroup.triceps],
    actions: const [JointAction.elbowExtension],
    rom: 3,
    stability: 1,
    machineLean: true,
    intimidation: IntimidationTier.moderate,
  ),

  // Core.
  _exercise(
    id: 'plank',
    name: 'Plank',
    slug: 'plank',
    role: BlockRole.core,
    movement: MovementClass.core,
    metric: MetricType.timed,
    equipment: ResistanceEquipment.bodyweight,
    support: SupportEquipment.mat,
    bw: 1,
    primary: const [MuscleGroup.core],
    secondary: const [MuscleGroup.glutes, MuscleGroup.shoulders],
    actions: const [JointAction.trunkBrace],
    rom: 1,
    stability: 3,
    machineLean: true,
  ),
  _exercise(
    id: 'cable-rope-kneeling-crunch',
    name: 'Cable Kneeling Crunch',
    slug: 'cable-rope-kneeling-crunch',
    role: BlockRole.core,
    movement: MovementClass.core,
    equipment: ResistanceEquipment.cable,
    bw: 0.15,
    primary: const [MuscleGroup.core],
    actions: const [JointAction.trunkFlexion],
    rom: 3,
    stability: 2,
    intimidation: IntimidationTier.moderate,
  ),
  _exercise(
    id: 'crunches',
    name: 'Crunches',
    slug: 'crunches',
    role: BlockRole.core,
    movement: MovementClass.core,
    metric: MetricType.repsOnly,
    equipment: ResistanceEquipment.bodyweight,
    support: SupportEquipment.mat,
    bw: 0.20,
    primary: const [MuscleGroup.core],
    actions: const [JointAction.trunkFlexion],
    rom: 2,
    stability: 1,
    machineLean: true,
  ),
  _exercise(
    id: 'elbow-side-plank',
    name: 'Side Plank',
    slug: 'elbow-side-plank',
    role: BlockRole.core,
    movement: MovementClass.core,
    metric: MetricType.timed,
    equipment: ResistanceEquipment.bodyweight,
    support: SupportEquipment.mat,
    laterality: Laterality.perSide,
    bw: 1,
    primary: const [MuscleGroup.obliques, MuscleGroup.core],
    secondary: const [MuscleGroup.shoulders],
    actions: const [JointAction.trunkBrace],
    rom: 1,
    stability: 4,
  ),
  _exercise(
    id: 'dead-bug',
    name: 'Dead Bug',
    slug: 'dead-bug',
    role: BlockRole.core,
    movement: MovementClass.core,
    metric: MetricType.repsOnly,
    equipment: ResistanceEquipment.bodyweight,
    support: SupportEquipment.mat,
    bw: 0.35,
    primary: const [MuscleGroup.core],
    actions: const [JointAction.trunkBrace],
    secondaryActions: const [JointAction.hipFlexion],
    rom: 2,
    stability: 2,
    machineLean: true,
  ),
];

final List<SwapEdge> _swapEdges = <SwapEdge>[
  ..._edgesFor(
    'dumbbell-goblet-squat',
    busy: const ['machine-leg-press', 'bodyweight-squat'],
    intimidating: const ['bodyweight-squat', 'machine-leg-press'],
    uncomfortable: const ['machine-leg-press', 'bodyweight-squat'],
    unavailable: const ['bodyweight-squat', 'machine-leg-press'],
  ),
  ..._edgesFor(
    'barbell-squat',
    busy: const ['dumbbell-goblet-squat', 'machine-leg-press'],
    intimidating: const ['dumbbell-goblet-squat', 'bodyweight-squat'],
    uncomfortable: const ['machine-leg-press', 'dumbbell-goblet-squat'],
    unavailable: const ['dumbbell-goblet-squat', 'machine-leg-press'],
  ),
  ..._edgesFor(
    'machine-leg-press',
    busy: const ['dumbbell-goblet-squat', 'bodyweight-squat'],
    intimidating: const ['bodyweight-squat', 'dumbbell-goblet-squat'],
    uncomfortable: const ['bodyweight-squat', 'dumbbell-goblet-squat'],
    unavailable: const ['dumbbell-goblet-squat', 'bodyweight-squat'],
  ),
  ..._edgesFor(
    'dumbbell-bulgarian-split-squat',
    busy: const ['bodyweight-reverse-lunge'],
    intimidating: const ['bodyweight-reverse-lunge'],
    uncomfortable: const ['bodyweight-reverse-lunge'],
    unavailable: const ['bodyweight-reverse-lunge'],
  ),
  ..._edgesFor(
    'bodyweight-squat',
    busy: const ['dumbbell-goblet-squat', 'machine-leg-press'],
    intimidating: const ['machine-leg-press', 'dumbbell-goblet-squat'],
    uncomfortable: const ['machine-leg-press', 'dumbbell-goblet-squat'],
    unavailable: const ['dumbbell-goblet-squat', 'machine-leg-press'],
  ),
  ..._edgesFor(
    'bodyweight-reverse-lunge',
    busy: const ['dumbbell-bulgarian-split-squat'],
    intimidating: const ['dumbbell-bulgarian-split-squat'],
    uncomfortable: const ['dumbbell-bulgarian-split-squat'],
    unavailable: const ['dumbbell-bulgarian-split-squat'],
  ),
  ..._edgesFor(
    'barbell-romanian-deadlift',
    busy: const ['dumbbell-romanian-deadlift', 'machine-back-extension'],
    intimidating: const [
      'dumbbell-romanian-deadlift',
      'machine-back-extension',
    ],
    uncomfortable: const ['machine-back-extension', 'cable-pull-through'],
    unavailable: const ['dumbbell-romanian-deadlift', 'cable-pull-through'],
  ),
  ..._edgesFor(
    'dumbbell-romanian-deadlift',
    busy: const ['cable-pull-through', 'machine-back-extension'],
    intimidating: const ['machine-back-extension', 'cable-pull-through'],
    uncomfortable: const ['machine-back-extension', 'cable-pull-through'],
    unavailable: const ['cable-pull-through', 'machine-back-extension'],
  ),
  ..._edgesFor(
    'barbell-deadlift',
    busy: const ['barbell-romanian-deadlift', 'dumbbell-romanian-deadlift'],
    intimidating: const [
      'dumbbell-romanian-deadlift',
      'machine-back-extension',
    ],
    uncomfortable: const ['machine-back-extension', 'cable-pull-through'],
    unavailable: const ['dumbbell-romanian-deadlift', 'machine-back-extension'],
  ),
  ..._edgesFor(
    'cable-pull-through',
    busy: const ['dumbbell-romanian-deadlift', 'machine-back-extension'],
    intimidating: const [
      'machine-back-extension',
      'dumbbell-romanian-deadlift',
    ],
    uncomfortable: const [
      'machine-back-extension',
      'dumbbell-romanian-deadlift',
    ],
    unavailable: const ['dumbbell-romanian-deadlift', 'machine-back-extension'],
  ),
  ..._edgesFor(
    'machine-back-extension',
    busy: const ['cable-pull-through', 'dumbbell-romanian-deadlift'],
    intimidating: const ['dumbbell-romanian-deadlift', 'cable-pull-through'],
    uncomfortable: const ['cable-pull-through', 'dumbbell-romanian-deadlift'],
    unavailable: const ['cable-pull-through', 'dumbbell-romanian-deadlift'],
  ),
  ..._denseRoleEdges(const [
    'barbell-hip-thrust',
    'dumbbell-glute-bridge',
    'dumbbell-hip-thrust',
    'machine-hip-abduction',
    'cable-standing-glute-kickback',
    'machine-glute-kickback',
  ]),
  ..._edgesFor(
    'dumbbell-bench-press',
    busy: const ['machine-chest-press', 'bodyweight-push-up'],
    intimidating: const ['machine-chest-press', 'bodyweight-push-up'],
    uncomfortable: const [
      'dumbbell-incline-bench-press',
      'machine-chest-press',
    ],
    unavailable: const ['bodyweight-push-up', 'machine-chest-press'],
  ),
  ..._edgesFor(
    'barbell-bench-press',
    busy: const ['dumbbell-bench-press', 'machine-chest-press'],
    intimidating: const ['machine-chest-press', 'bodyweight-push-up'],
    uncomfortable: const [
      'dumbbell-incline-bench-press',
      'machine-chest-press',
    ],
    unavailable: const ['dumbbell-bench-press', 'machine-chest-press'],
  ),
  ..._edgesFor(
    'machine-chest-press',
    busy: const ['dumbbell-bench-press', 'bodyweight-push-up'],
    intimidating: const [
      'bodyweight-push-up',
      'dumbbell-seated-overhead-press',
    ],
    uncomfortable: const ['dumbbell-incline-bench-press', 'bodyweight-push-up'],
    unavailable: const ['dumbbell-bench-press', 'bodyweight-push-up'],
  ),
  ..._edgesFor(
    'dumbbell-incline-bench-press',
    busy: const ['dumbbell-bench-press', 'machine-chest-press'],
    intimidating: const ['machine-chest-press', 'bodyweight-push-up'],
    uncomfortable: const ['dumbbell-bench-press', 'machine-chest-press'],
    unavailable: const ['dumbbell-bench-press', 'machine-chest-press'],
  ),
  ..._edgesFor(
    'dumbbell-seated-overhead-press',
    busy: const ['machine-chest-press', 'bodyweight-push-up'],
    intimidating: const ['machine-chest-press', 'bodyweight-push-up'],
    uncomfortable: const [
      'dumbbell-incline-bench-press',
      'machine-chest-press',
    ],
    unavailable: const ['machine-chest-press', 'bodyweight-push-up'],
  ),
  ..._edgesFor(
    'bodyweight-push-up',
    busy: const ['machine-chest-press', 'dumbbell-bench-press'],
    intimidating: const [
      'machine-chest-press',
      'dumbbell-seated-overhead-press',
    ],
    uncomfortable: const [
      'machine-chest-press',
      'dumbbell-incline-bench-press',
    ],
    unavailable: const ['machine-chest-press', 'dumbbell-bench-press'],
  ),
  ..._edgesFor(
    'machine-pulldown',
    busy: const ['bodyweight-assisted-chin-up', 'machine-seated-cable-row'],
    intimidating: const [
      'machine-seated-cable-row',
      'machine-rear-deltoid-row',
    ],
    uncomfortable: const [
      'machine-seated-cable-row',
      'machine-rear-deltoid-row',
    ],
    unavailable: const [
      'machine-seated-cable-row',
      'bodyweight-assisted-chin-up',
    ],
  ),
  ..._edgesFor(
    'machine-seated-cable-row',
    busy: const ['machine-pulldown', 'machine-rear-deltoid-row'],
    intimidating: const ['machine-pulldown', 'machine-rear-deltoid-row'],
    uncomfortable: const ['machine-pulldown', 'machine-rear-deltoid-row'],
    unavailable: const ['machine-pulldown', 'machine-rear-deltoid-row'],
  ),
  ..._edgesFor(
    'bodyweight-assisted-chin-up',
    busy: const ['machine-pulldown', 'machine-seated-cable-row'],
    intimidating: const ['machine-pulldown', 'machine-seated-cable-row'],
    uncomfortable: const ['machine-pulldown', 'machine-seated-cable-row'],
    unavailable: const ['machine-pulldown', 'machine-seated-cable-row'],
  ),
  ..._edgesFor(
    'machine-rear-deltoid-row',
    busy: const ['machine-seated-cable-row', 'machine-pulldown'],
    intimidating: const ['machine-seated-cable-row', 'machine-pulldown'],
    uncomfortable: const ['machine-seated-cable-row', 'machine-pulldown'],
    unavailable: const ['machine-seated-cable-row', 'machine-pulldown'],
  ),
  ..._edgesFor(
    'plank',
    busy: const ['elbow-side-plank'],
    intimidating: const ['elbow-side-plank'],
    uncomfortable: const ['elbow-side-plank'],
    unavailable: const ['elbow-side-plank'],
  ),
  ..._edgesFor(
    'elbow-side-plank',
    busy: const ['plank'],
    intimidating: const ['plank'],
    uncomfortable: const ['plank'],
    unavailable: const ['plank'],
  ),
  ..._edgesFor(
    'cable-rope-kneeling-crunch',
    busy: const ['crunches', 'dead-bug'],
    intimidating: const ['dead-bug', 'crunches'],
    uncomfortable: const ['dead-bug', 'crunches'],
    unavailable: const ['crunches', 'dead-bug'],
  ),
  ..._edgesFor(
    'crunches',
    busy: const ['dead-bug', 'cable-rope-kneeling-crunch'],
    intimidating: const ['dead-bug', 'cable-rope-kneeling-crunch'],
    uncomfortable: const ['dead-bug', 'cable-rope-kneeling-crunch'],
    unavailable: const ['dead-bug', 'cable-rope-kneeling-crunch'],
  ),
  ..._edgesFor(
    'dead-bug',
    busy: const ['crunches', 'cable-rope-kneeling-crunch'],
    intimidating: const ['crunches', 'cable-rope-kneeling-crunch'],
    uncomfortable: const ['crunches', 'cable-rope-kneeling-crunch'],
    unavailable: const ['crunches', 'cable-rope-kneeling-crunch'],
  ),
];

ExerciseData _exercise({
  required String id,
  required String name,
  required String slug,
  required BlockRole role,
  required MovementClass movement,
  required ResistanceEquipment equipment,
  required double bw,
  required List<MuscleGroup> primary,
  required List<JointAction> actions,
  MetricType metric = MetricType.loadReps,
  SupportEquipment support = SupportEquipment.none,
  Laterality laterality = Laterality.bilateral,
  List<MuscleGroup> secondary = const <MuscleGroup>[],
  List<JointAction> secondaryActions = const <JointAction>[],
  int rom = 3,
  int stability = 3,
  IntimidationTier intimidation = IntimidationTier.low,
  bool machineLean = false,
  bool seated = false,
}) => ExerciseData(
  id: id,
  name: name,
  slug: slug,
  blockRole: role,
  movementClass: movement,
  metricType: metric,
  resistanceEquipment: equipment,
  supportEquipment: support,
  laterality: laterality,
  bwContribution: bw,
  targetMuscles: <MuscleTarget>[
    for (final muscle in primary) MuscleTarget.primary(muscle),
    for (final muscle in secondary) MuscleTarget.secondary(muscle),
  ],
  primaryJointActions: actions,
  secondaryJointActions: secondaryActions,
  romRank: rom,
  stabilityRank: stability,
  intimidationTier: intimidation,
  machineLeanOk: machineLean,
  seatedVariant: seated,
  setupSteps: <String>[
    'Find the setup shown for $name and choose the easiest starting position.',
    'Adjust the contact points so the movement path feels natural.',
    'Brace gently and rehearse one slow repetition without strain.',
    'Start the working set only when the setup feels stable.',
  ],
  shouldFeel: 'The listed target muscles working through a controlled range.',
  stopIf:
      'Stop for sharp or joint pain, dizziness, or loss of a stable position.',
  findIt:
      'Look for the equipment named in $name; ask the trainer on duty if unsure.',
  dos: const <String>[
    'Move with control.',
    'Keep breathing.',
    'Finish each clean repetition.',
  ],
  donts: const <String>[
    'Do not chase load at the expense of form.',
    'Do not bounce through the hardest point.',
    'Do not continue through sharp pain.',
  ],
);

List<SwapEdge> _edgesFor(
  String fromId, {
  required List<String> busy,
  required List<String> intimidating,
  required List<String> uncomfortable,
  required List<String> unavailable,
}) {
  final result = <SwapEdge>[];
  void add(SwapReason reason, List<String> ids) {
    for (var rank = 0; rank < ids.length; rank++) {
      result.add(
        SwapEdge(fromId: fromId, toId: ids[rank], reason: reason, rank: rank),
      );
    }
  }

  add(SwapReason.busy, busy);
  add(SwapReason.intimidating, intimidating);
  add(SwapReason.uncomfortable, uncomfortable);
  add(SwapReason.unavailable, unavailable);
  return result;
}

List<SwapEdge> _denseRoleEdges(List<String> exerciseIds) {
  final result = <SwapEdge>[];
  for (var fromIndex = 0; fromIndex < exerciseIds.length; fromIndex++) {
    final alternatives = <String>[
      for (var offset = 1; offset < exerciseIds.length; offset++)
        exerciseIds[(fromIndex + offset) % exerciseIds.length],
    ];
    result.addAll(
      _edgesFor(
        exerciseIds[fromIndex],
        busy: alternatives,
        intimidating: alternatives.reversed.toList(growable: false),
        uncomfortable: <String>[...alternatives.skip(1), alternatives.first],
        unavailable: alternatives,
      ),
    );
  }
  return result;
}
